services:
  messenger-web:
    container_name: messenger-web
    restart: unless-stopped
    build:
      context: .
      args:
        VITE_API_URL: /api
        VITE_YANDEX_CLIENT_ID: ${VITE_YANDEX_CLIENT_ID}
        VITE_REDIRECT_URI: ${VITE_REDIRECT_URI}
    ports:
      - "8081:80"
